import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
    sv: {
        nav: {
            services: 'VÅRA TJÄNSTER',
            about: 'OM OSS',
            contact: 'KONTAKTA OSS'
        },
        hero: {
            title: 'Tid för det som är viktigt.',
            desc: 'Professionella tjänster inom städning och solcellsmontage. Vi hjälper både privatpersoner och företag med pålitliga och kvalitativa tjänster.',
            inputPlaceholder: 'Ditt postnummer',
            cta: 'VÄLJ TJÄNST',
            note: 'Se ditt pris direkt på 30 sekunder',
            trustpilot: '4.8/5 Trustpilot',
            customers: '50,000+ Kunder'
        },
        services: {
            title: 'Våra Tjänster',
            subtitle: 'Från skinande rena hem till hållbar energi.',
            readMore: 'Läs mer',
            cleaningServicesHeader: 'Städtjänster',
            solar: { title: 'Solcellsmontage', desc: 'Komplett installation av solceller för både villa och företag.' },
            cleaning: { title: 'Hemstädning', desc: 'Regelbunden städning för en enklare vardag.' },
            deepCleaning: { title: 'Storstädning', desc: 'En grundlig rengöring från golv till tak.' },
            window: { title: 'Fönsterputs', desc: 'Skinande rena fönster, året om.' },
            moving: { title: 'Flyttstädning', desc: 'Vi städar så att du kan lämna över med gott samvete.' },
            garden: { title: 'Trädgårdshjälp', desc: 'Från gräsklippning till beskärning.' },
            office: { title: 'Kontorsstädning', desc: 'En ren arbetsplats för bättre fokus.' },
            brf: { title: 'För BRF', desc: 'Renare trapphus och gemensamma utrymmen.' },
            visning: { title: 'Visningsstädning', desc: 'Inför försäljning eller visning.' },
            construction: { title: 'Byggstädning', desc: 'Professionell städning efter renovering.' },
            staircase: { title: 'Trappstädning', desc: 'För fastighetsägare och BRF.' }
        },
        footer: {
            legal: '© 2024 Z&C Group. Alla rättigheter förbehållna.',
            terms: 'Villkor',
            cookies: 'Cookies',
            privacy: 'Integritet'
        },
        common: {
            home: 'Hem',
            cleaningGuarantee: 'Städgaranti',
            trainedStaff: 'Utbildad personal',
            insurance: 'Ansvarsförsäkring',
            firstName: 'Förnamn',
            lastName: 'Efternamn',
            email: 'E-post',
            phone: 'Telefon',
            address: 'Adress',
            postalCode: 'Postnummer',
            city: 'Ort',
            propertyType: 'Bostadstyp',
            selectType: 'Välj typ',
            apartment: 'Lägenhet',
            villa: 'Villa',
            townhouse: 'Radhus',
            other: 'Annat',
            size: 'Storlek (m²)',
            selectSize: 'Välj storlek',
            preferredDate: 'Önskat datum',
            time: 'Tid',
            selectTime: 'Välj tid',
            morning: 'Förmiddag (08-12)',
            afternoon: 'Eftermiddag (12-17)',
            message: 'Meddelande',
            messagePlaceholder: 'Berätta gärna mer om din bostad eller speciella önskemål...',
            acceptTerms: 'Jag accepterar',
            terms: 'villkoren',
            priceAfterRut: 'Pris efter RUT-avdrag',
            regularPrice: 'Ordinarie',
            sending: 'Skickar...',
            successMessage: 'Tack! Vi har mottagit din förfrågan och återkommer inom kort.',
            errorMessage: 'Något gick fel. Vänligen försök igen eller kontakta oss direkt.',
            formIntro: 'Fyll i formuläret så kontaktar vi dig för att bekräfta bokningen.',
            upTo: 'Upp till',
        },
        values: {
            title: 'Mer än bara service',
            safe: 'Tryggt',
            safeDesc: 'Vår personal är noga utvald, utbildad och försäkrad. Vi har kollektivavtal och schyssta villkor – en självklarhet för oss.',
            flexible: 'Flexibelt',
            flexibleDesc: 'Avboka eller boka om när livet händer. Ingen bindningstid på våra abonnemang, och du kan alltid pausa vid behov.',
            simple: 'Enkelt',
            simpleDesc: 'Med vår app har du full kontroll. Se bokningar, fakturor och kommunicera direkt med din städare eller kundservice.',
            cta: 'Läs mer om oss'
        },
        description: {
            title: 'I vår värld är det detaljerna som gör skillnaden',
            text: 'Vi finns där du finns. Med verksamhet i <a href="#">Stockholm</a>, <a href="#">Göteborg</a>, <a href="#">Malmö</a>, <a href="#">Uppsala</a>, <a href="#">Västerås</a> och många fler orter, är vi aldrig långt borta. Oavsett om du behöver <a href="/tjanster/hemstadning">hemstädning</a> varje vecka eller en engångsinsats inför <a href="/tjanster/storstadning">storstädningen</a>, så har vi lösningen för dig.',
            quote: '"Det räcker inte att möta förväntningarna. Vi vill överträffa dem."'
        },
        app: {
            title: 'Allt du behöver på ett ställe',
            text: 'Som kund hos Z&C Group får du tillgång till vår smidiga app. Här samlar vi allt som rör ditt hem, så att du kan lägga tiden på annat.',
            cta: 'Läs mer om appen',
            features: ['Se dina bokningar', 'Boka med timbank', 'Avboka & omboka smidigt', 'Uppdatera städinstruktioner', 'Lämna omdömen', 'Hantera fakturor', 'Få personliga erbjudanden', 'Tips & guider']
        },
        testimonial: {
            text: 'Att komma hem till ett nystädat hem på torsdagar är veckans höjdpunkt. Det ger mig lugn och tid att fokusera på familjen.',
            author: 'Anna, Stockholm',
            role: 'Kund sedan 2018'
        },
        recruitment: {
            title: 'Vill du jobba på Z&C Group?',
            desc: 'Vi söker ständigt efter nya stjärnor. Oavsett om du vill städa, fixa i trädgården eller jobba på kontoret.',
            cta: 'Besök vår karriärsida',
            roles: ['Hemstädare', 'Fönsterputsare', 'Flyttstädare', 'Kundtjänst', 'Säljare']
        },
        storstadning: {
            title: 'Storstädning',
            subtitle: 'Storstädning för ett fräscht och välstädat hem eller arbetsplats. Vi utför en grundlig rengöring av alla ytor för att ge ditt utrymme ny energi och ett långvarigt rent resultat.',
            bookTitle: 'Boka din storstädning',
            bookBtn: 'Boka storstädning',
            whatIncluded: 'Vad ingår i Storstädning?',
            allRooms: 'Alla rum',
            allRoomsList: [
                'Dammsugning och moppning av golv',
                'Dammsugning av mattor även under om möjlighet finns',
                'Dammsugning av klädda och stoppade möbler',
                'Dammtorkning av golvlister, karmar, eluttag, dörrar, fönsterbrädor',
                'Putsning av speglar',
                'Tömning av papperskorgar',
                'Damning av möbler, lampor och tavlor',
                'Dammtorkning av fria ytor på hyllor',
                'Dammtorkning av väggar, element, fria ytor samt ovanpå skåp och garderober'
            ],
            kitchen: 'Kök',
            kitchenList: [
                'Rengöring av mikrovågsugn in- och utvändigt',
                'Rengöring av köksfläkt samt ventiler (ej inuti)',
                'Rengöring av kyl och frys utvändigt',
                'Rengöring av diskmaskin in- och utvändigt',
                'Rengöring av skåp, hyllor och lådor utvändigt',
                'Avtorkning av köksluckor in- och utvändigt',
                'Rengöring av diskho och diskbänk',
                'Rengöring av spis och kakel ovanför diskbänk',
                'Tömning och avtorkning av sopkorg',
                'Rengöring in- och utvändigt i skåp där sopbehållare finns',
                'Torkning av vitvaror'
            ],
            bathroom: 'Toalett och badrum',
            bathroomList: [
                'Rengöring av kakelväggar och fogar i duschutrymme (om möjligt)',
                'Rengöring av golv och synliga rör',
                'Golvbrunnar och ventiler rengörs utvändigt',
                'Rengöring av alla förvaringsutrymmen utvändigt',
                'Rengöring av all sanitet, även under badkaret',
                'Tvättmaskin, torktumlare och torkskåp rengörs utvändigt'
            ],
            bathroomNote: '* Fronten av badkar/jacuzzi nedmonteras och återställes av kund',
            addons: 'Tilläggstjänster till storstädning',
            addonsList: [
                'Fönsterputs',
                'Rengöring av ugn invändig',
                'Rengöring av kylskåp invändig',
                'Rengöring av köksskåp och lådor invändig',
                'Bi area som balkong, vind, förråd och garage'
            ],
            infoTitle: 'Inför storstädning',
            infoText: 'Vi rekommenderar att lösa föremål såsom leksaker, kläder, disk m.m. plockas undan för att uppnå bästa möjliga städresultat.',
            infoNote: 'Målade ytor såsom väggar och tak endast dammtorkas med torr trasa för att undvika att färgen skadas eller släpper.'
        },
        flyttstadning: {
            title: 'Flyttstädning',
            subtitle: 'Professionell flyttstädning för en trygg överlämning. Vi ser till att bostaden blir noggrant städad och godkänd vid besiktning, så att du kan lämna ditt hem med gott samvete.',
            bookTitle: 'Boka flyttstädning',
            bookBtn: 'Skicka bokningsförfrågan',
            whatIncluded: 'Vad ingår i flyttstädning?',
            servicesList: [
                'Dammsugning och våttorkning av alla golv',
                'Rengöring av kök och vitvaror (in- och utvändigt)',
                'Badrum och toalett rengörs noggrant',
                'Fönsterputsning (in- och utvändigt)',
                'Rengöring av garderober och skåp',
                'Avtorkning av dörrar och karmar',
                'Rengöring av golvlister och socklar',
                'Städgaranti vid besiktning'
            ],
            additionalTitle: 'Tilläggstjänster',
            additionalServices: [
                { name: 'Fönsterputs av halvinglasad balkong', price: '400 kr' },
                { name: 'Fönsterputs av helglasad balkong', price: '600 kr' },
                { name: 'Inglasad uterum (pris efter antal fönster)', price: 'Ca 800 kr' },
                { name: 'Helgtillägg', price: '600 kr' },
                { name: 'Storhelgtillägg', price: '1000 kr' },
                { name: 'Kamin: tömning av aska, glasrengöring, avtorkning', price: '200 kr' },
                { name: 'Fönsterputs av 3-glas', price: '20 kr/glas' },
                { name: 'Sopning av balkong', price: '150 kr' },
                { name: 'Städning av biytor (förråd, garage, balkonger)', price: 'Offert' }
            ],
            excludedTitle: 'Ingår inte i flyttstädning',
            excludedList: [
                'Väggar och tak (kan bokas som tillägg)',
                'Balkonger och uteplatser (kan bokas som tillägg)',
                'Persienner',
                'Fönster utvändigt ovan markplan',
                'Förråd och garage (kan bokas som tillägg)'
            ],
            notIncluded: 'Kan bokas som tillägg',
            infoTitle: 'Bra att veta',
            infoText: 'Bostaden ska vara tom vid städning. Vi rekommenderar att alla personliga tillhörigheter är borta innan vi börjar. Städgaranti gäller vid besiktning inom 3 dagar.',
            infoNote: 'Lämna gärna nycklar eller portkod i förväg för en smidig process.'
        },
        byggstadning: {
            title: 'Byggstädning',
            subtitle: 'Professionell byggstädning efter renovering eller nybyggnation. Vi säkerställer att lokalerna är inflyttningsklara och fria från byggdamm och smuts.',
            bookTitle: 'Boka byggstädning',
            bookBtn: 'Skicka förfrågan',
            projectType: 'Projekttyp',
            selectProjectType: 'Välj projekttyp',
            newBuild: 'Nybyggnation',
            renovation: 'Renovering',
            commercial: 'Kommersiell lokal',
            industrial: 'Industrilokal',
            cleaningType: 'Typ av städning',
            selectCleaningType: 'Välj typ av städning',
            roughCleaning: 'Grovstädning',
            fineCleaning: 'Finstädning',
            bothTypes: 'Både grov- och finstädning',
            area: 'Yta (m²)',
            before: 'FÖRE',
            after: 'EFTER'
        },
        kontorsstadning: {
            title: 'Kontorsstädning',
            subtitle: 'Professionell kontorsstädning för en ren och inspirerande arbetsmiljö. Vi anpassar städningen efter era behov och arbetstider.',
            bookTitle: 'Boka kontorsstädning',
            bookBtn: 'Skicka förfrågan',
            companyName: 'Företagsnamn',
            orgNumber: 'Org.nummer',
            officeSize: 'Kontorsstorlek',
            selectOfficeSize: 'Välj storlek',
            employees: 'Antal anställda',
            selectEmployees: 'Välj antal',
            frequency: 'Städfrekvens',
            selectFrequency: 'Välj frekvens',
            daily: 'Dagligen',
            weeklyMultiple: 'Flera gånger/vecka',
            weekly: 'En gång/vecka',
            biweekly: 'Varannan vecka',
            monthly: 'En gång/månad'
        },
        trappstadning: {
            title: 'Trappstädning',
            subtitle: 'Professionell trappstädning för fastighetsägare och bostadsrättsföreningar. Regelbunden rengöring av trapphus och gemensamma utrymmen.',
            bookTitle: 'Boka trappstädning',
            bookBtn: 'Skicka förfrågan',
            floors: 'Antal våningar',
            selectFloors: 'Välj antal',
            frequency: 'Städfrekvens',
            additionalServices: 'Tilläggstjänster',
            windowCleaning: 'Fönsterputs i trapphus',
            elevatorCleaning: 'Hisstädning',
            laundryCleaning: 'Tvättstugestädning',
            garageCleaning: 'Garagestädning',
            recycleCleaning: 'Soprum/återvinning'
        },
        fonsterputs: {
            title: 'Fönsterputs',
            subtitle: 'Professionell fönsterputsning för skinande rena fönster. Vi putsar alla typer av fönster, året runt.',
            bookTitle: 'Boka fönsterputs',
            bookBtn: 'Skicka förfrågan',
            windowType: 'Fönstertyp',
            numberOfWindows: 'Antal fönster',
            insideOutside: 'In- och utsida'
        },
        visningsstadning: {
            title: 'Visningsstädning',
            subtitle: 'Professionell visningsstädning inför försäljning eller uthyrning. Vi gör ditt hem presentabelt och inbjudande för potentiella köpare.',
            bookTitle: 'Boka visningsstädning',
            bookBtn: 'Skicka förfrågan'
        },
        solcellsmontage: {
            title: 'Mekanisk montering av montagesystem och solpaneler',
            subtitle: 'Vi är en specialiserad montagepartner som arbetar som underentreprenör åt etablerade solcells- och installationsföretag i hela Sverige.',
            heroBadge: 'Montagepartner för solcellsbranschen',
            heroDesc2: 'Vi utför enbart den mekaniska monteringen av montagesystem och solpaneler.',
            contactCta: 'Kontakta oss',
            servicesCta: 'Våra tjänster',
            targetTitle: 'Våra tjänster riktar sig till företag',
            targetDesc: 'Våra tjänster riktar sig till företag i branschen som behöver en pålitlig, flexibel och kvalitetsfokuserad montageentreprenör för tak- och markinstallationer.',
            targetHighlightBold: 'Ni tillhandahåller ritningar och tekniskt underlag',
            targetHighlightText: '– och vi ansvarar för ett säkert, effektivt och fackmannamässigt montage enligt gällande branschstandarder.',
            featuresTitle: 'Vad vi erbjuder',
            featuresSubtitle: 'Som specialiserad underentreprenör fokuserar vi helt på mekanisk montering',
            mechanicalTitle: 'Mekanisk montering',
            mechanicalDesc: 'Vi utför enbart den mekaniska monteringen av montagesystem och solpaneler – inget el-arbete.',
            roofTitle: 'Tak & markinstallationer',
            roofDesc: 'Erfarenhet av alla typer av tak och markbaserade installationer över hela Sverige.',
            documentsTitle: 'Ni tillhandahåller underlag',
            documentsDesc: 'Ni levererar ritningar och tekniskt underlag – vi ansvarar för ett fackmannamässigt montage.',
            qualityTitle: 'Kvalitet & säkerhet',
            qualityDesc: 'Säkert, effektivt montage enligt gällande branschstandarder och säkerhetsföreskrifter.',
            whyUs: 'Varför välja oss?',
            specializedPartner: 'Specialiserad montagepartner',
            experiencedInstallers: 'Erfarna montörer',
            flexibleCapacity: 'Flexibel kapacitet',
            qualityFocus: 'Kvalitetsfokus',
            industryStandards: 'Branschstandarder',
            efficientExecution: 'Effektivt utförande',
            experience: 'Erfarenhet',
            experienceDesc: 'Över 500 installationer genomförda.',
            warranty: 'Garanti',
            warrantyDesc: 'Upp till 25 års garanti på paneler.',
            certified: 'Certifierade',
            certifiedDesc: 'Alla våra montörer är certifierade.',
            contactTitle: 'Kontakta oss',
            contactSubtitle: 'Är ni ett solcells- eller installationsföretag som söker en pålitlig montagepartner? Kontakta oss för att diskutera ert projekt.',
            insured: 'Försäkrad',
            companyName: 'Företagsnamn',
            contactPerson: 'Kontaktperson',
            name: 'Namn',
            messagePlaceholder: 'Berätta om ert projekt...',
            roofType: 'Taktyp',
            selectRoofType: 'Välj taktyp',
            tileRoof: 'Tegelpannor',
            metalRoof: 'Plåttak',
            flatRoof: 'Platt tak',
            otherRoof: 'Övrigt',
            sendRequest: 'Skicka förfrågan',
            process: 'Så fungerar samarbetet',
            step1: 'Kontakt',
            step1Desc: 'Ni kontaktar oss med information om ert projekt och behov.',
            step2: 'Underlag',
            step2Desc: 'Ni tillhandahåller ritningar, specifikationer och tekniskt underlag.',
            step3: 'Planering',
            step3Desc: 'Vi planerar montaget och koordinerar med er tidplan.',
            step4: 'Montage',
            step4Desc: 'Vi utför den mekaniska monteringen enligt branschstandarder.'
        }
    },
    en: {
        nav: {
            services: 'OUR SERVICES',
            about: 'ABOUT US',
            contact: 'CONTACT US'
        },
        hero: {
            title: 'Time for what matters.',
            desc: 'Professional services in cleaning and solar panel installation. We help both individuals and companies with reliable and high-quality services.',
            inputPlaceholder: 'Your zip code',
            cta: 'Calculate price',
            note: 'See your price instantly in 30 seconds',
            trustpilot: '4.8/5 Trustpilot',
            customers: '50,000+ Customers'
        },
        services: {
            title: 'Our Services',
            subtitle: 'From sparkling clean homes to sustainable energy.',
            readMore: 'Read more',
            cleaningServicesHeader: 'Cleaning Services',
            solar: { title: 'Solar Installation', desc: 'Complete installation of solar panels for both villas and businesses.' },
            cleaning: { title: 'Home Cleaning', desc: 'Regular cleaning for a simpler everyday life.' },
            deepCleaning: { title: 'Deep Cleaning', desc: 'A thorough clean from floor to ceiling.' },
            window: { title: 'Window Cleaning', desc: 'Sparkling clean windows, all year round.' },
            moving: { title: 'Move-out Cleaning', desc: 'We clean so you can handover with peace of mind.' },
            garden: { title: 'Garden Help', desc: 'From lawn mowing to pruning.' },
            office: { title: 'Office Cleaning', desc: 'A clean workplace for better focus.' },
            brf: { title: 'For HOA/BRF', desc: 'Cleaner stairwells and common areas.' },
            visning: { title: 'Pre-sale Cleaning', desc: 'Before selling or viewing.' },
            construction: { title: 'Post-construction Cleaning', desc: 'Professional cleaning post renovation.' },
            staircase: { title: 'Stairwell Cleaning', desc: 'For property owners and HOAs.' }
        },
        footer: {
            legal: '© 2024 Z&C Group. All rights reserved.',
            terms: 'Terms',
            cookies: 'Cookies',
            privacy: 'Privacy'
        },
        common: {
            home: 'Home',
            cleaningGuarantee: 'Cleaning guarantee',
            trainedStaff: 'Trained staff',
            insurance: 'Liability insurance',
            firstName: 'First name',
            lastName: 'Last name',
            email: 'Email',
            phone: 'Phone',
            address: 'Address',
            postalCode: 'Postal code',
            city: 'City',
            propertyType: 'Property type',
            selectType: 'Select type',
            apartment: 'Apartment',
            villa: 'Villa',
            townhouse: 'Townhouse',
            other: 'Other',
            size: 'Size (m²)',
            selectSize: 'Select size',
            preferredDate: 'Preferred date',
            time: 'Time',
            selectTime: 'Select time',
            morning: 'Morning (08-12)',
            afternoon: 'Afternoon (12-17)',
            message: 'Message',
            messagePlaceholder: 'Tell us more about your home or special requests...',
            acceptTerms: 'I accept the',
            terms: 'terms and conditions',
            priceAfterRut: 'Price after RUT deduction',
            regularPrice: 'Regular',
            sending: 'Sending...',
            successMessage: 'Thank you! We have received your request and will get back to you shortly.',
            errorMessage: 'Something went wrong. Please try again or contact us directly.',
            formIntro: 'Fill in the form and we will contact you to confirm the booking.',
            upTo: 'Up to',
        },
        values: {
            title: 'More than just service',
            safe: 'Safe',
            safeDesc: 'Our staff is carefully selected, trained, and insured. We have collective agreements and fair conditions – a given for us.',
            flexible: 'Flexible',
            flexibleDesc: 'Cancel or reschedule when life happens. No commitment on our subscriptions, and you can always pause when needed.',
            simple: 'Simple',
            simpleDesc: 'With our app you have full control. See bookings, invoices and communicate directly with your cleaner or customer service.',
            cta: 'Read more about us'
        },
        description: {
            title: 'In our world, it\'s the details that make the difference',
            text: 'We are where you are. With operations in <a href="#">Stockholm</a>, <a href="#">Gothenburg</a>, <a href="#">Malmö</a>, <a href="#">Uppsala</a>, <a href="#">Västerås</a> and many more locations, we are never far away. Whether you need <a href="/tjanster/hemstadning">home cleaning</a> every week or a one-time effort before <a href="/tjanster/storstadning">deep cleaning</a>, we have the solution for you.',
            quote: '"It\'s not enough to meet expectations. We want to exceed them."'
        },
        app: {
            title: 'Everything you need in one place',
            text: 'As a customer of Z&C Group you get access to our convenient app. Here we gather everything related to your home, so you can spend your time on other things.',
            cta: 'Read more about the app',
            features: ['View your bookings', 'Book with time bank', 'Cancel & reschedule easily', 'Update cleaning instructions', 'Leave reviews', 'Manage invoices', 'Get personal offers', 'Tips & guides']
        },
        testimonial: {
            text: 'Coming home to a freshly cleaned home on Thursdays is the highlight of the week. It gives me peace and time to focus on the family.',
            author: 'Anna, Stockholm',
            role: 'Customer since 2018'
        },
        recruitment: {
            title: 'Want to work at Z&C Group?',
            desc: 'We are constantly looking for new stars. Whether you want to clean, work in the garden, or work in the office.',
            cta: 'Visit our careers page',
            roles: ['Home cleaner', 'Window cleaner', 'Move-out cleaner', 'Customer service', 'Sales']
        },
        storstadning: {
            title: 'Deep Cleaning',
            subtitle: 'Deep cleaning for a fresh and well-kept home or workplace. We perform a thorough cleaning of all surfaces to give your space new energy and a long-lasting clean result.',
            bookTitle: 'Book your deep cleaning',
            bookBtn: 'Book deep cleaning',
            whatIncluded: 'What is included in Deep Cleaning?',
            allRooms: 'All rooms',
            allRoomsList: [
                'Vacuuming and mopping of floors',
                'Vacuuming carpets, including underneath when possible',
                'Vacuuming upholstered furniture',
                'Wiping baseboards, frames, outlets, doors, window sills',
                'Polishing mirrors',
                'Emptying trash cans',
                'Dusting furniture, lamps, and paintings',
                'Wiping free surfaces on shelves',
                'Wiping walls, radiators, free surfaces, and tops of cabinets and wardrobes'
            ],
            kitchen: 'Kitchen',
            kitchenList: [
                'Cleaning microwave inside and outside',
                'Cleaning kitchen fan and vents (not inside)',
                'Cleaning fridge and freezer outside',
                'Cleaning dishwasher inside and outside',
                'Cleaning cabinets, shelves, and drawers outside',
                'Wiping kitchen cabinet doors inside and outside',
                'Cleaning sink and countertop',
                'Cleaning stove and tiles above countertop',
                'Emptying and wiping trash can',
                'Cleaning inside and outside cabinets with trash bins',
                'Wiping appliances'
            ],
            bathroom: 'Toilet and bathroom',
            bathroomList: [
                'Cleaning tile walls and grout in shower area (if possible)',
                'Cleaning floors and visible pipes',
                'Floor drains and vents cleaned externally',
                'Cleaning all storage spaces externally',
                'Cleaning all sanitary fixtures, including under bathtub',
                'Washing machine, dryer, and drying cabinet cleaned externally'
            ],
            bathroomNote: '* Front of bathtub/jacuzzi removed and restored by customer',
            addons: 'Additional services for deep cleaning',
            addonsList: [
                'Window cleaning',
                'Internal oven cleaning',
                'Internal fridge cleaning',
                'Internal kitchen cabinet and drawer cleaning',
                'Secondary areas like balcony, attic, storage, and garage'
            ],
            infoTitle: 'Before deep cleaning',
            infoText: 'We recommend that loose items such as toys, clothes, dishes, etc. are put away to achieve the best possible cleaning result.',
            infoNote: 'Painted surfaces such as walls and ceilings are only dry-wiped with a dry cloth to avoid damage to the paint.'
        },
        flyttstadning: {
            title: 'Move-out Cleaning',
            subtitle: 'Professional move-out cleaning for a safe handover. We ensure the home is thoroughly cleaned and approved at inspection, so you can leave your home with a clear conscience.',
            bookTitle: 'Book move-out cleaning',
            bookBtn: 'Send booking request',
            whatIncluded: 'What is included in move-out cleaning?',
            servicesList: [
                'Vacuuming and wet wiping of all floors',
                'Cleaning kitchen and appliances (inside and outside)',
                'Bathroom and toilet thoroughly cleaned',
                'Window cleaning (inside and outside)',
                'Cleaning wardrobes and cabinets',
                'Wiping doors and frames',
                'Cleaning baseboards and skirting boards',
                'Cleaning guarantee at inspection'
            ],
            additionalTitle: 'Additional services',
            additionalServices: [
                { name: 'Window cleaning of semi-glazed balcony', price: '400 kr' },
                { name: 'Window cleaning of fully-glazed balcony', price: '600 kr' },
                { name: 'Glazed patio (price per number of windows)', price: 'Approx. 800 kr' },
                { name: 'Weekend surcharge', price: '600 kr' },
                { name: 'Holiday surcharge', price: '1000 kr' },
                { name: 'Fireplace: ash removal, glass cleaning, wiping', price: '200 kr' },
                { name: 'Triple-glazed window cleaning', price: '20 kr/pane' },
                { name: 'Balcony sweeping', price: '150 kr' },
                { name: 'Cleaning of secondary areas (storage, garage, balconies)', price: 'Quote' }
            ],
            excludedTitle: 'Not included in move-out cleaning',
            excludedList: [
                'Walls and ceilings (can be booked as add-on)',
                'Balconies and patios (can be booked as add-on)',
                'Blinds',
                'Exterior windows above ground floor',
                'Storage and garage (can be booked as add-on)'
            ],
            notIncluded: 'Can be booked as add-on',
            infoTitle: 'Good to know',
            infoText: 'The home should be empty during cleaning. We recommend that all personal belongings are removed before we start. Cleaning guarantee applies at inspection within 3 days.',
            infoNote: 'Please leave keys or entry code in advance for a smooth process.'
        },
        byggstadning: {
            title: 'Post-construction Cleaning',
            subtitle: 'Professional post-construction cleaning after renovation or new build. We ensure the premises are move-in ready and free from construction dust and dirt.',
            bookTitle: 'Book post-construction cleaning',
            bookBtn: 'Send request',
            projectType: 'Project type',
            selectProjectType: 'Select project type',
            newBuild: 'New construction',
            renovation: 'Renovation',
            commercial: 'Commercial space',
            industrial: 'Industrial space',
            cleaningType: 'Cleaning type',
            selectCleaningType: 'Select cleaning type',
            roughCleaning: 'Rough cleaning',
            fineCleaning: 'Fine cleaning',
            bothTypes: 'Both rough and fine cleaning',
            area: 'Area (m²)',
            before: 'BEFORE',
            after: 'AFTER'
        },
        kontorsstadning: {
            title: 'Office Cleaning',
            subtitle: 'Professional office cleaning for a clean and inspiring work environment. We adapt the cleaning to your needs and working hours.',
            bookTitle: 'Book office cleaning',
            bookBtn: 'Send request',
            companyName: 'Company name',
            orgNumber: 'Org. number',
            officeSize: 'Office size',
            selectOfficeSize: 'Select size',
            employees: 'Number of employees',
            selectEmployees: 'Select number',
            frequency: 'Cleaning frequency',
            selectFrequency: 'Select frequency',
            daily: 'Daily',
            weeklyMultiple: 'Several times/week',
            weekly: 'Once/week',
            biweekly: 'Every other week',
            monthly: 'Once/month'
        },
        trappstadning: {
            title: 'Stairwell Cleaning',
            subtitle: 'Professional stairwell cleaning for property owners and housing associations. Regular cleaning of stairwells and common areas.',
            bookTitle: 'Book stairwell cleaning',
            bookBtn: 'Send request',
            floors: 'Number of floors',
            selectFloors: 'Select number',
            frequency: 'Cleaning frequency',
            additionalServices: 'Additional services',
            windowCleaning: 'Window cleaning in stairwell',
            elevatorCleaning: 'Elevator cleaning',
            laundryCleaning: 'Laundry room cleaning',
            garageCleaning: 'Garage cleaning',
            recycleCleaning: 'Waste/recycling room'
        },
        fonsterputs: {
            title: 'Window Cleaning',
            subtitle: 'Professional window cleaning for sparkling clean windows. We clean all types of windows, all year round.',
            bookTitle: 'Book window cleaning',
            bookBtn: 'Send request',
            windowType: 'Window type',
            numberOfWindows: 'Number of windows',
            insideOutside: 'Inside and outside'
        },
        visningsstadning: {
            title: 'Pre-sale Cleaning',
            subtitle: 'Professional pre-sale cleaning before selling or renting. We make your home presentable and inviting for potential buyers.',
            bookTitle: 'Book pre-sale cleaning',
            bookBtn: 'Send request'
        },
        solcellsmontage: {
            title: 'Mechanical mounting of mounting systems and solar panels',
            subtitle: 'We are a specialized assembly partner working as a subcontractor for established solar and installation companies throughout Sweden.',
            heroBadge: 'Assembly partner for the solar industry',
            heroDesc2: 'We perform only the mechanical mounting of mounting systems and solar panels.',
            contactCta: 'Contact us',
            servicesCta: 'Our services',
            targetTitle: 'Our services are aimed at businesses',
            targetDesc: 'Our services are aimed at companies in the industry that need a reliable, flexible and quality-focused assembly contractor for roof and ground installations.',
            targetHighlightBold: 'You provide drawings and technical documentation',
            targetHighlightText: '– and we are responsible for safe, efficient and professional assembly according to current industry standards.',
            featuresTitle: 'What we offer',
            featuresSubtitle: 'As a specialized subcontractor, we focus entirely on mechanical mounting',
            mechanicalTitle: 'Mechanical mounting',
            mechanicalDesc: 'We perform only the mechanical mounting of mounting systems and solar panels – no electrical work.',
            roofTitle: 'Roof & ground installations',
            roofDesc: 'Experience with all types of roof and ground-based installations throughout Sweden.',
            documentsTitle: 'You provide documentation',
            documentsDesc: 'You deliver drawings and technical documentation – we are responsible for professional assembly.',
            qualityTitle: 'Quality & safety',
            qualityDesc: 'Safe, efficient assembly according to current industry standards and safety regulations.',
            whyUs: 'Why choose us?',
            specializedPartner: 'Specialized assembly partner',
            experiencedInstallers: 'Experienced installers',
            flexibleCapacity: 'Flexible capacity',
            qualityFocus: 'Quality focus',
            industryStandards: 'Industry standards',
            efficientExecution: 'Efficient execution',
            experience: 'Experience',
            experienceDesc: 'Over 500 installations completed.',
            warranty: 'Warranty',
            warrantyDesc: 'Up to 25 years warranty on panels.',
            certified: 'Certified',
            certifiedDesc: 'All our installers are certified.',
            contactTitle: 'Contact us',
            contactSubtitle: 'Are you a solar or installation company looking for a reliable assembly partner? Contact us to discuss your project.',
            insured: 'Insured',
            companyName: 'Company name',
            contactPerson: 'Contact person',
            name: 'Name',
            messagePlaceholder: 'Tell us about your project...',
            roofType: 'Roof type',
            selectRoofType: 'Select roof type',
            tileRoof: 'Tile roof',
            metalRoof: 'Metal roof',
            flatRoof: 'Flat roof',
            otherRoof: 'Other',
            sendRequest: 'Send request',
            process: 'How the collaboration works',
            step1: 'Contact',
            step1Desc: 'You contact us with information about your project and needs.',
            step2: 'Documentation',
            step2Desc: 'You provide drawings, specifications and technical documentation.',
            step3: 'Planning',
            step3Desc: 'We plan the assembly and coordinate with your schedule.',
            step4: 'Assembly',
            step4Desc: 'We perform the mechanical mounting according to industry standards.'
        }
    },
    es: {
        nav: {
            services: 'NUESTROS SERVICIOS',
            about: 'SOBRE NOSOTROS',
            contact: 'CONTÁCTANOS'
        },
        hero: {
            title: 'Tiempo para lo que importa.',
            desc: 'Servicios profesionales de limpieza e instalación de paneles solares. Ayudamos a particulares y empresas con servicios fiables y de alta calidad.',
            inputPlaceholder: 'Tu código postal',
            cta: 'Calcular precio',
            note: 'Ver precio al instante en 30 segundos',
            trustpilot: '4.8/5 Trustpilot',
            customers: '50,000+ Clientes'
        },
        services: {
            title: 'Nuestros Servicios',
            subtitle: 'Desde hogares impecables hasta energía sostenible.',
            readMore: 'Leer más',
            cleaningServicesHeader: 'Servicios de Limpieza',
            solar: { title: 'Instalación Solar', desc: 'Instalación completa de paneles solares para casas particulares y empresas.' },
            cleaning: { title: 'Limpieza de Hogar', desc: 'Limpieza regular para un día a día más sencillo.' },
            deepCleaning: { title: 'Limpieza a Fondo', desc: 'Una limpieza minuciosa de suelo a techo.' },
            window: { title: 'Limpieza de Cristales', desc: 'Cristales relucientes durante todo el año.' },
            moving: { title: 'Limpieza por Mudanza', desc: 'Limpiamos para que entregues las llaves con tranquilidad.' },
            garden: { title: 'Ayuda en Jardín', desc: 'Desde cortar el césped hasta podar.' },
            office: { title: 'Limpieza de Oficinas', desc: 'Un lugar de trabajo limpio para un mejor enfoque.' },
            brf: { title: 'Para Comunidades', desc: 'Escaleras y zonas comunes más limpias.' },
            visning: { title: 'Limpieza de Visita', desc: 'Antes de vender o enseñar la casa.' },
            construction: { title: 'Limpieza de Obra', desc: 'Limpieza profesional tras reformas.' },
            staircase: { title: 'Limpieza de Escaleras', desc: 'Para comunidades y propietarios.' }
        },
        footer: {
            legal: '© 2024 Z&C Group. Todos los derechos reservados.',
            terms: 'Términos',
            cookies: 'Cookies',
            privacy: 'Privacidad'
        },
        common: {
            home: 'Inicio',
            cleaningGuarantee: 'Garantía de limpieza',
            trainedStaff: 'Personal capacitado',
            insurance: 'Seguro de responsabilidad',
            firstName: 'Nombre',
            lastName: 'Apellido',
            email: 'Correo electrónico',
            phone: 'Teléfono',
            address: 'Dirección',
            postalCode: 'Código postal',
            city: 'Ciudad',
            propertyType: 'Tipo de propiedad',
            selectType: 'Seleccionar tipo',
            apartment: 'Apartamento',
            villa: 'Villa',
            townhouse: 'Adosado',
            other: 'Otro',
            size: 'Tamaño (m²)',
            selectSize: 'Seleccionar tamaño',
            preferredDate: 'Fecha deseada',
            time: 'Hora',
            selectTime: 'Seleccionar hora',
            morning: 'Mañana (08-12)',
            afternoon: 'Tarde (12-17)',
            message: 'Mensaje',
            messagePlaceholder: 'Cuéntanos más sobre tu vivienda o solicitudes especiales...',
            acceptTerms: 'Acepto los',
            terms: 'términos y condiciones',
            priceAfterRut: 'Precio con deducción RUT',
            regularPrice: 'Precio normal',
            sending: 'Enviando...',
            successMessage: '¡Gracias! Hemos recibido tu solicitud y te contactaremos pronto.',
            errorMessage: 'Algo salió mal. Por favor intenta de nuevo o contáctanos directamente.',
            formIntro: 'Rellena el formulario y te contactaremos para confirmar la reserva.',
            upTo: 'Hasta',
        },
        values: {
            title: 'Más que solo un servicio',
            safe: 'Seguro',
            safeDesc: 'Nuestro personal es cuidadosamente seleccionado, capacitado y asegurado. Tenemos convenios colectivos y condiciones justas – algo natural para nosotros.',
            flexible: 'Flexible',
            flexibleDesc: 'Cancela o reprograma cuando la vida lo requiera. Sin permanencia en nuestras suscripciones, y siempre puedes pausar cuando lo necesites.',
            simple: 'Sencillo',
            simpleDesc: 'Con nuestra app tienes control total. Ve reservas, facturas y comunícate directamente con tu limpiador o servicio al cliente.',
            cta: 'Leer más sobre nosotros'
        },
        description: {
            title: 'En nuestro mundo, son los detalles los que marcan la diferencia',
            text: 'Estamos donde tú estás. Con operaciones en <a href="#">Estocolmo</a>, <a href="#">Gotemburgo</a>, <a href="#">Malmö</a>, <a href="#">Uppsala</a>, <a href="#">Västerås</a> y muchas más localidades, nunca estamos lejos. Ya sea que necesites <a href="/tjanster/hemstadning">limpieza del hogar</a> cada semana o una intervención puntual antes de una <a href="/tjanster/storstadning">limpieza a fondo</a>, tenemos la solución para ti.',
            quote: '"No basta con cumplir las expectativas. Queremos superarlas."'
        },
        app: {
            title: 'Todo lo que necesitas en un solo lugar',
            text: 'Como cliente de Z&C Group tienes acceso a nuestra práctica app. Aquí reunimos todo lo relacionado con tu hogar, para que puedas dedicar tu tiempo a otras cosas.',
            cta: 'Leer más sobre la app',
            features: ['Ver tus reservas', 'Reservar con banco de horas', 'Cancelar y reprogramar fácilmente', 'Actualizar instrucciones de limpieza', 'Dejar opiniones', 'Gestionar facturas', 'Recibir ofertas personalizadas', 'Consejos y guías']
        },
        testimonial: {
            text: 'Llegar a casa un jueves y encontrarla recién limpia es lo mejor de la semana. Me da tranquilidad y tiempo para disfrutar de la familia.',
            author: 'Anna, Estocolmo',
            role: 'Cliente desde 2018'
        },
        recruitment: {
            title: '¿Quieres trabajar en Z&C Group?',
            desc: 'Buscamos constantemente nuevas estrellas. Ya sea que quieras limpiar, trabajar en el jardín o en la oficina.',
            cta: 'Visita nuestra página de empleo',
            roles: ['Limpiador/a del hogar', 'Limpiador/a de cristales', 'Limpiador/a de mudanzas', 'Atención al cliente', 'Ventas']
        },
        storstadning: {
            title: 'Limpieza a Fondo',
            subtitle: 'Limpieza a fondo para un hogar o lugar de trabajo fresco y bien cuidado. Realizamos una limpieza minuciosa de todas las superficies para dar a tu espacio nueva energía y un resultado duradero.',
            bookTitle: 'Reserva tu limpieza a fondo',
            bookBtn: 'Reservar limpieza a fondo',
            whatIncluded: '¿Qué incluye la Limpieza a Fondo?',
            allRooms: 'Todas las habitaciones',
            allRoomsList: [
                'Aspirado y fregado de suelos',
                'Aspirado de alfombras, incluso por debajo si es posible',
                'Aspirado de muebles tapizados',
                'Limpieza de rodapiés, marcos, enchufes, puertas, alféizares',
                'Limpieza de espejos',
                'Vaciado de papeleras',
                'Desempolvado de muebles, lámparas y cuadros',
                'Limpieza de superficies libres en estantes',
                'Limpieza de paredes, radiadores, superficies libres y parte superior de armarios'
            ],
            kitchen: 'Cocina',
            kitchenList: [
                'Limpieza de microondas por dentro y por fuera',
                'Limpieza de campana extractora y rejillas (no interior)',
                'Limpieza exterior de nevera y congelador',
                'Limpieza de lavavajillas por dentro y por fuera',
                'Limpieza exterior de armarios, estantes y cajones',
                'Limpieza de puertas de cocina por dentro y por fuera',
                'Limpieza de fregadero y encimera',
                'Limpieza de vitrocerámica y azulejos sobre la encimera',
                'Vaciado y limpieza del cubo de basura',
                'Limpieza interior y exterior de armarios con cubos de basura',
                'Limpieza de electrodomésticos'
            ],
            bathroom: 'Baño y aseo',
            bathroomList: [
                'Limpieza de azulejos y juntas en zona de ducha (si es posible)',
                'Limpieza de suelo y tuberías visibles',
                'Desagües y rejillas limpiadas exteriormente',
                'Limpieza exterior de todos los espacios de almacenamiento',
                'Limpieza de todos los sanitarios, incluso debajo de la bañera',
                'Lavadora, secadora y armario de secado limpiados exteriormente'
            ],
            bathroomNote: '* El frente de la bañera/jacuzzi es desmontado y restaurado por el cliente',
            addons: 'Servicios adicionales para limpieza a fondo',
            addonsList: [
                'Limpieza de cristales',
                'Limpieza interior del horno',
                'Limpieza interior de la nevera',
                'Limpieza interior de armarios y cajones de cocina',
                'Áreas secundarias como balcón, ático, trastero y garaje'
            ],
            infoTitle: 'Antes de la limpieza a fondo',
            infoText: 'Recomendamos retirar objetos sueltos como juguetes, ropa, platos, etc. para lograr el mejor resultado de limpieza posible.',
            infoNote: 'Las superficies pintadas como paredes y techos solo se limpian en seco con un paño para evitar dañar la pintura.'
        },
        flyttstadning: {
            title: 'Limpieza por Mudanza',
            subtitle: 'Limpieza profesional por mudanza para una entrega segura. Nos aseguramos de que la vivienda quede limpia a fondo y aprobada en la inspección, para que puedas entregar tu hogar con tranquilidad.',
            bookTitle: 'Reservar limpieza por mudanza',
            bookBtn: 'Enviar solicitud de reserva',
            whatIncluded: '¿Qué incluye la limpieza por mudanza?',
            servicesList: [
                'Aspirado y fregado de todos los suelos',
                'Limpieza de cocina y electrodomésticos (interior y exterior)',
                'Baño y aseo limpiados a fondo',
                'Limpieza de cristales (interior y exterior)',
                'Limpieza de armarios y gabinetes',
                'Limpieza de puertas y marcos',
                'Limpieza de rodapiés y zócalos',
                'Garantía de limpieza en inspección'
            ],
            additionalTitle: 'Servicios adicionales',
            additionalServices: [
                { name: 'Limpieza de cristales de balcón semi-acristalado', price: '400 kr' },
                { name: 'Limpieza de cristales de balcón totalmente acristalado', price: '600 kr' },
                { name: 'Terraza acristalada (precio según número de ventanas)', price: 'Aprox. 800 kr' },
                { name: 'Suplemento fin de semana', price: '600 kr' },
                { name: 'Suplemento festivos', price: '1000 kr' },
                { name: 'Chimenea: vaciado de ceniza, limpieza de cristal, limpieza', price: '200 kr' },
                { name: 'Limpieza de cristales triple', price: '20 kr/cristal' },
                { name: 'Barrido de balcón', price: '150 kr' },
                { name: 'Limpieza de áreas secundarias (trastero, garaje, balcones)', price: 'Presupuesto' }
            ],
            excludedTitle: 'No incluido en la limpieza por mudanza',
            excludedList: [
                'Paredes y techos (se puede reservar como extra)',
                'Balcones y terrazas (se puede reservar como extra)',
                'Persianas',
                'Ventanas exteriores sobre planta baja',
                'Trastero y garaje (se puede reservar como extra)'
            ],
            notIncluded: 'Se puede reservar como extra',
            infoTitle: 'Bueno saber',
            infoText: 'La vivienda debe estar vacía durante la limpieza. Recomendamos que todas las pertenencias personales estén retiradas antes de comenzar. La garantía de limpieza aplica en inspección dentro de 3 días.',
            infoNote: 'Por favor deja las llaves o código de entrada con antelación para un proceso fluido.'
        },
        byggstadning: {
            title: 'Limpieza de Obra',
            subtitle: 'Limpieza profesional de obra tras renovación o nueva construcción. Nos aseguramos de que las instalaciones estén listas para mudarse y libres de polvo y suciedad de construcción.',
            bookTitle: 'Reservar limpieza de obra',
            bookBtn: 'Enviar solicitud',
            projectType: 'Tipo de proyecto',
            selectProjectType: 'Seleccionar tipo de proyecto',
            newBuild: 'Nueva construcción',
            renovation: 'Renovación',
            commercial: 'Local comercial',
            industrial: 'Local industrial',
            cleaningType: 'Tipo de limpieza',
            selectCleaningType: 'Seleccionar tipo de limpieza',
            roughCleaning: 'Limpieza gruesa',
            fineCleaning: 'Limpieza fina',
            bothTypes: 'Ambas (gruesa y fina)',
            area: 'Superficie (m²)',
            before: 'ANTES',
            after: 'DESPUÉS'
        },
        kontorsstadning: {
            title: 'Limpieza de Oficinas',
            subtitle: 'Limpieza profesional de oficinas para un entorno de trabajo limpio e inspirador. Adaptamos la limpieza a sus necesidades y horarios.',
            bookTitle: 'Reservar limpieza de oficinas',
            bookBtn: 'Enviar solicitud',
            companyName: 'Nombre de la empresa',
            orgNumber: 'Nº de organización',
            officeSize: 'Tamaño de oficina',
            selectOfficeSize: 'Seleccionar tamaño',
            employees: 'Número de empleados',
            selectEmployees: 'Seleccionar cantidad',
            frequency: 'Frecuencia de limpieza',
            selectFrequency: 'Seleccionar frecuencia',
            daily: 'Diariamente',
            weeklyMultiple: 'Varias veces/semana',
            weekly: 'Una vez/semana',
            biweekly: 'Cada dos semanas',
            monthly: 'Una vez/mes'
        },
        trappstadning: {
            title: 'Limpieza de Escaleras',
            subtitle: 'Limpieza profesional de escaleras para propietarios y comunidades. Limpieza regular de escaleras y áreas comunes.',
            bookTitle: 'Reservar limpieza de escaleras',
            bookBtn: 'Enviar solicitud',
            floors: 'Número de pisos',
            selectFloors: 'Seleccionar cantidad',
            frequency: 'Frecuencia de limpieza',
            additionalServices: 'Servicios adicionales',
            windowCleaning: 'Limpieza de ventanas en escalera',
            elevatorCleaning: 'Limpieza de ascensor',
            laundryCleaning: 'Limpieza de lavandería',
            garageCleaning: 'Limpieza de garaje',
            recycleCleaning: 'Cuarto de basuras/reciclaje'
        },
        fonsterputs: {
            title: 'Limpieza de Cristales',
            subtitle: 'Limpieza profesional de cristales para ventanas relucientes. Limpiamos todo tipo de ventanas, durante todo el año.',
            bookTitle: 'Reservar limpieza de cristales',
            bookBtn: 'Enviar solicitud',
            windowType: 'Tipo de ventana',
            numberOfWindows: 'Número de ventanas',
            insideOutside: 'Interior y exterior'
        },
        visningsstadning: {
            title: 'Limpieza de Visita',
            subtitle: 'Limpieza profesional de visita antes de vender o alquilar. Hacemos que tu hogar luzca presentable y acogedor para los posibles compradores.',
            bookTitle: 'Reservar limpieza de visita',
            bookBtn: 'Enviar solicitud'
        },
        solcellsmontage: {
            title: 'Montaje mecánico de sistemas de montaje y paneles solares',
            subtitle: 'Somos un socio de montaje especializado que trabaja como subcontratista para empresas solares e instaladoras establecidas en toda Suecia.',
            heroBadge: 'Socio de montaje para la industria solar',
            heroDesc2: 'Realizamos únicamente el montaje mecánico de sistemas de montaje y paneles solares.',
            contactCta: 'Contáctanos',
            servicesCta: 'Nuestros servicios',
            targetTitle: 'Nuestros servicios están dirigidos a empresas',
            targetDesc: 'Nuestros servicios están dirigidos a empresas del sector que necesitan un contratista de montaje fiable, flexible y enfocado en la calidad para instalaciones en techo y suelo.',
            targetHighlightBold: 'Ustedes proporcionan planos y documentación técnica',
            targetHighlightText: '– y nosotros nos encargamos de un montaje seguro, eficiente y profesional según los estándares actuales de la industria.',
            featuresTitle: 'Lo que ofrecemos',
            featuresSubtitle: 'Como subcontratista especializado, nos enfocamos completamente en el montaje mecánico',
            mechanicalTitle: 'Montaje mecánico',
            mechanicalDesc: 'Realizamos únicamente el montaje mecánico de sistemas de montaje y paneles solares – sin trabajo eléctrico.',
            roofTitle: 'Instalaciones en techo y suelo',
            roofDesc: 'Experiencia con todo tipo de instalaciones en techo y suelo en toda Suecia.',
            documentsTitle: 'Ustedes proporcionan la documentación',
            documentsDesc: 'Ustedes entregan planos y documentación técnica – nosotros nos encargamos del montaje profesional.',
            qualityTitle: 'Calidad y seguridad',
            qualityDesc: 'Montaje seguro y eficiente según los estándares y regulaciones de seguridad vigentes.',
            whyUs: '¿Por qué elegirnos?',
            specializedPartner: 'Socio de montaje especializado',
            experiencedInstallers: 'Instaladores experimentados',
            flexibleCapacity: 'Capacidad flexible',
            qualityFocus: 'Enfoque en calidad',
            industryStandards: 'Estándares de la industria',
            efficientExecution: 'Ejecución eficiente',
            experience: 'Experiencia',
            experienceDesc: 'Más de 500 instalaciones realizadas.',
            warranty: 'Garantía',
            warrantyDesc: 'Hasta 25 años de garantía en paneles.',
            certified: 'Certificados',
            certifiedDesc: 'Todos nuestros instaladores están certificados.',
            contactTitle: 'Contáctanos',
            contactSubtitle: '¿Es usted una empresa solar o de instalación que busca un socio de montaje fiable? Contáctenos para discutir su proyecto.',
            insured: 'Asegurado',
            companyName: 'Nombre de la empresa',
            contactPerson: 'Persona de contacto',
            name: 'Nombre',
            messagePlaceholder: 'Cuéntenos sobre su proyecto...',
            roofType: 'Tipo de techo',
            selectRoofType: 'Seleccionar tipo de techo',
            tileRoof: 'Tejas',
            metalRoof: 'Techo metálico',
            flatRoof: 'Techo plano',
            otherRoof: 'Otro',
            sendRequest: 'Enviar solicitud',
            process: 'Cómo funciona la colaboración',
            step1: 'Contacto',
            step1Desc: 'Nos contactan con información sobre su proyecto y necesidades.',
            step2: 'Documentación',
            step2Desc: 'Ustedes proporcionan planos, especificaciones y documentación técnica.',
            step3: 'Planificación',
            step3Desc: 'Planificamos el montaje y coordinamos con su calendario.',
            step4: 'Montaje',
            step4Desc: 'Realizamos el montaje mecánico según los estándares de la industria.'
        }
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('sv');

    const t = (path) => {
        const keys = path.split('.');
        let result = translations[language];
        for (const key of keys) {
            if (result) result = result[key];
        }
        return result || path;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
